api/urls.py
from django.urls import path
from .views import Main
from .views import Login
from .views import Logout

from .views import Organisation_List
from .views import Organisation_Page
from .views import Organisation_Edit
from .views import Organisation_Delete
from .views import Organisation_Create
from .views import Organisation_Invite
from .views import Organisation_Select

from .views import Worker_List
from .views import Worker_Delete

from .views import Category_List
from .views import Category_Add
from .views import Category_Delete

from .views import Product_Page
from .views import Product_Delete
from .views import Product_Edit
from .views import Product_List
from .views import Product_Add


app_name = 'api'
urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),

    path('org_list/', Organisation_List.as_view(), name='org_list'),
    path('org_page/<int:org_id>/', Organisation_Page.as_view(), name='org_page'),
    path('org_page/edit/<int:org_id>/', Organisation_Edit.as_view(), name='org_edit'),
    path('org_page/delete/<int:org_id>/', Organisation_Delete.as_view(), name='org_delete'),
    path('org_page/create/', Organisation_Create.as_view(), name='org_create'),
    path('org_page/invite/<int:org_id>', Organisation_Invite.as_view(), name='org_invite'),
    path('org_page/select/<int:org_id>', Organisation_Select.as_view(), name='org_select'),

    path('worker_list', Worker_List.as_view(), name='worker_list'),
    path('worker_delete/<int:worker_tg>', Worker_Delete.as_view(), name='worker_delete'),

    path('category_list/', Category_List.as_view(), name='category_list'),
    path('category_add/', Category_Add.as_view(), name='category_add'),
    path('category_delete/<int:category_id>', Category_Delete.as_view(), name='category_delete'),

    path('product_list/', Product_List.as_view(), name='product_list'),      
    path('product/<int:product_id>', Product_Page.as_view(), name='product_page'),
    path('product/delete/<int:product_id>', Product_Delete.as_view(), name='product_delete'),
    path('product/edit/<int:product_id>', Product_Edit.as_view(), name='product_edit'),
    path('product/add/', Product_Add.as_view(), name='product_add'),
]

server/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("bot", include("bot.urls")),
    path('', include('api.urls')),
]

api/models.py
from django.db import models
from django.utils import timezone

class TelegramUsers(models.Model):
    session_id = models.CharField(max_length=56, unique=True)
    tg_id = models.CharField(max_length=56, default="no-auth")
    name = models.CharField(max_length=56, default="no-auth")
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.tg_id
    class Meta:
        ordering = ['-created']

class Orgs(models.Model):
    boss_tg = models.CharField(max_length=56, default="no-auth")
    name = models.CharField(max_length=56, default="no-name")
    created = models.DateTimeField(default=timezone.now)
    workers = models.ManyToManyField(TelegramUsers)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-created']

class Categories(models.Model):
    name = models.CharField(max_length=56, default="no-name")
    org = models.ForeignKey(Orgs, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-created']

class Products(models.Model):
    name = models.CharField(max_length=56, default="no-name")
    org = models.ForeignKey(Orgs, on_delete=models.CASCADE)
    description = models.TextField(default=None)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-created']
        

api/views.py
from django.views import View
from django.shortcuts import render, redirect
from .models import TelegramUsers
from .models import Orgs
from .models import Categories
from .models import Products

class Main(View):
    def get(self, request):
        return render(request, 'main.html')
    
class Login(View):
    def get(self, request):
        session_id = request.session["session_id"]
        telegram_login_url = f"https://t.me/sh_login_testing_bot?start={session_id}"
        return redirect(telegram_login_url)
    
class Logout(View):
    def get(self, request):
        session_id = request.session["session_id"]
        if TelegramUsers.objects.filter(session_id=session_id).exists():
            user = TelegramUsers.objects.get(session_id=session_id)
            user.session_id = "None"
            user.save()

        request.session["session_id"]=None
        request.session["auth"]=None
        request.session["name"]=None
        request.session["org_select"]=None
        return redirect("/")
    
class Organisation_List(View):
    def get(self, request):
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)
        orgs = Orgs.objects.filter(workers=user)
        return render(request, 'org_list.html', {"orgs":orgs})
       
class Organisation_Page(View):
    def get(self, request, org_id):
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})

        org = Orgs.objects.get(id=org_id)
        if not org.workers.filter(session_id=session_id).exists():
            info = "Вы не состоите в этой организации"
            return render(request, 'info.html', {"info":info})
        
        return render(request, "org_page.html", {"org":org})


class Organisation_Edit(View):
    def post(self, request, org_id):
        name = request.POST["input_field"]
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})

        org = Orgs.objects.get(id=org_id)
        if user.tg_id != org.boss_tg:
            info = "У вас нет прав не смену названия"
            return render(request, 'info.html', {"info":info}) 
        
        org.name=name
        org.save()
        return redirect('api:org_list')
    
class Organisation_Delete(View):
    def post(self, request, org_id):
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})

        org = Orgs.objects.get(id=org_id)
        if user.tg_id != org.boss_tg:
            info = "У вас нет прав на удаление"
            return render(request, 'info.html', {"info":info}) 
        
        org.delete()
        request.session["org_select"]=None
        return redirect('api:org_list')
    
class Organisation_Create(View):
    def post(self, request):
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)
        name = request.POST["input_field"]

        org=Orgs.objects.create(name=name, boss_tg=user.tg_id)
        org.workers.add(user)
        org.save()
        return redirect('api:org_list')
    
class Organisation_Invite(View):
    def get(self, request, org_id):
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})
        
        org = Orgs.objects.get(id=org_id)
        if org.workers.filter(id=user.id).exists():
            info = "Вы уже состоите в этой организации"
            return render(request, 'info.html', {"info":info})
        
        org.workers.add(user)
        return redirect('api:org_list')
    
class Organisation_Select(View):
    def get(self, request, org_id):
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)
        org = Orgs.objects.get(id=org_id)
        if not org.workers.filter(session_id=session_id).exists():
            info = "Вы не состоите в этой организации"
            return render(request, 'info.html', {"info":info})
        
        request.session["org_select"]=org.id
        return redirect('api:org_list')

class Worker_List(View):
    def get(self, request):
        org_id = request.session["org_select"]
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})
        
        org = Orgs.objects.get(id=org_id)
        if not org.workers.filter(session_id=session_id).exists():
            info = "Вы не состоите в этой организации"
            return render(request, 'info.html', {"info":info})
        
        workers = org.workers.all()
        return render(request, 'worker_list.html', {"workers":workers})

class Worker_Delete(View):
    def post(self, request, worker_tg):
        org_id = request.session["org_select"]
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})
        
        org = Orgs.objects.get(id=org_id)
        if user.tg_id != org.boss_tg:
            info = "У вас нет прав на увольнение"
            return render(request, 'info.html', {"info":info}) 
        
        if user.tg_id == str(worker_tg):
            info = "Нельзя уволить начальника организации!"
            return render(request, 'info.html', {"info":info})
        
        worker = TelegramUsers.objects.get(tg_id=worker_tg)
        org.workers.remove(worker)
        org.save()
        return redirect('api:worker_list')
    
class Category_List(View):
    def get(self, request):
        org_id = request.session["org_select"]
        session_id = request.session["session_id"]

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})
        
        org = Orgs.objects.get(id=org_id)
        if not org.workers.filter(session_id=session_id).exists():
            info = "Вы не состоите в этой организации"
            return render(request, 'info.html', {"info":info})
        
        categories = Categories.objects.filter(org=org)
        return render(request, 'category_list.html', {"categories":categories})
    
class Category_Add(View):
    def post(self, request):
        category_name = request.POST["input_field"]
        org_id = request.session["org_select"]
        session_id = request.session["session_id"]

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})
        
        org = Orgs.objects.get(id=org_id)
        if not org.workers.filter(session_id=session_id).exists():
            info = "Вы не состоите в этой организации"
            return render(request, 'info.html', {"info":info})

        category_list = Categories.objects.filter(org=org_id)
        for c in category_list:
            if category_name.lower() == c.name.lower():
                info = "У вас уже есть такая категория"
                return render(request, 'info.html', {"info":info})

        Categories.objects.create(name=category_name, org=org)    
        return redirect('api:category_list')

class Category_Delete(View):
    def post(self, request, category_id):
        org_id = request.session["org_select"]
        session_id = request.session["session_id"]
        user = TelegramUsers.objects.get(session_id=session_id)

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})
        
        org = Orgs.objects.get(id=org_id)
        if not org.workers.filter(session_id=session_id).exists():
            info = "Вы не состоите в этой организации"
            return render(request, 'info.html', {"info":info})
        
        if user.tg_id != org.boss_tg:
            info = "У вас нет прав на удаление категорий!"
            return render(request, 'info.html', {"info":info}) 

        if not Categories.objects.filter(id=category_id).exists():
            info = "Нет такой категории"
            return render(request, 'info.html', {"info":info})
        
        category = Categories.objects.get(id=category_id)
        category.delete()
        return redirect('api:category_list')

class Product_List(View):
    def get(self, request):
        org_id = request.session["org_select"]
        session_id = request.session["session_id"]

        if not Orgs.objects.filter(id=org_id).exists():
            info = "Нет такой организации"
            return render(request, 'info.html', {"info":info})
        
        org = Orgs.objects.get(id=org_id)
        if not org.workers.filter(session_id=session_id).exists():
            info = "Вы не состоите в этой организации"
            return render(request, 'info.html', {"info":info})
        
        products = Products.objects.filter(org=org).select_related('category', 'org').order_by('category__name')

api/templates/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}bitstock{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/svg+xml" href="{% static 'icon.svg' %}">
{% tailwind_css %}
</head>
<body class="bg-zinc-800">
    {% if request.session.auth %}
    <div class="bg-zinc-400 flex pl-10 items-center justify-between">
        <div class="flex">
            <form action="{% url 'api:main' %}" method="GET">
                <button class="hover:bg-zinc-500 h-10 w-40 items-center flex justify-center duration-500">{{request.session.name}}</button>
            </form>

            <form action="{% url 'api:org_list' %}" method="GET">
                <button class="hover:bg-zinc-500 h-10 w-40 items-center flex justify-center duration-500">Организации</button>
            </form>

            {% if request.session.org_select %}
            <form action="{% url 'api:worker_list' %}" method="GET">
                <button class="hover:bg-zinc-500 h-10 w-40 items-center flex justify-center duration-500">Сотрудники</button>
            </form>

            <form action="{% url 'api:category_list' %}" method="GET">
                <button class="hover:bg-zinc-500 h-10 w-40 items-center flex justify-center duration-500">Категории</button>
            </form>

            <form action="{% url 'api:product_list' %}" method="GET">
                <button class="hover:bg-zinc-500 h-10 w-40 items-center flex justify-center duration-500">Товары</button>
            </form>

            <form action=""" method="GET">
                <button class="hover:bg-zinc-500 h-10 w-40 items-center flex justify-center duration-500">Сделки</button>
            </form>
            {% endif %}

        </div>

        <form action="{% url 'api:logout' %}" method="GET">
            <button class="hover:bg-zinc-500 h-10 w-20 items-center flex justify-center duration-500">Logout</button>
        </form>
    </div>


    {% endif %}
    <div class="px-10 mt-32">
    {% block content %}{% endblock %}
    </div>
</body>
</html>

api/templates/category_list.html
{% extends 'base.html' %}
{% block title %}
category list
{% endblock %}
{% block content %}
{% load static %}


<div>
    <div class="w-1/3">
    {% for category in categories %}
        <div class="flex gap-1 mt-1">
            <div class="flex bg-zinc-400 h-10 px-4 rounded justify-between items-center basis-2/3">
                <div>{{category.name}}</div>
            </div>

            <div>
                <form action="{% url 'api:category_delete' category_id=category.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="duration-500 hover:bg-red-500 bg-red-400 h-10 px-4 rounded basis-1/3">Удалить</button>
                </form>
            </div>
        </div>
    {% endfor %}
        <div>
            <form class="mt-10" method="post" action="{% url 'api:category_add' %}">
                {% csrf_token %}
                <input autocomplete="off"  type="text" id="input_field" name="input_field" required maxlength="56" class="h-10 w-2/3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
                <button type="submit" class="duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Создать</button>
                <label for="input_field" class="block text-sm font-medium text-zinc-300">Введите название категории</label>
            </form>
        </div>
    </div>
</div>

{% endblock %}

api/templates/info.html
{% extends 'base.html' %}
{% block title %}
info
{% endblock %}
{% block content %}
{% load static %}

<div class="text-white">
    {{info}}
</div>


{% endblock %}

api/templates/main.html
{% extends 'base.html' %}
{% block title %}
main
{% endblock %}
{% block content %}

{% if request.session.auth != True %}
<div class="flex justify-center items-center h-screen">
  <form class="" action="{% url 'api:login' %}" method="GET">
    <button class="text-lg duration-500 hover:bg-zinc-500 bg-zinc-400 h-20 w-48 text-center rounded-3xl" type="submit">telegram login</button>
  </form>
</div> 
{% endif %}
{% endblock %}

api/templates/org.html
{% extends 'base.html' %}
{% block title %}
orgs
{% endblock %}
{% block content %}
{% load static %}

<div class="flex justify-between">
    <div>
        <form class="" method="post">
            {% csrf_token %}
            <input autocomplete="off" placeholder="{{org.name}}" type="text" id="input_field" name="input_field" required maxlength="56" class="h-10 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
            <button type="submit" class="duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Заменить</button>
            <label for="input_field" class="block text-sm font-medium text-zinc-300">Введите новое название организации</label>
        </form>
    </div>

    <div>
        <form class="" method="post" action="{% url 'api:org_del' org_id=org.id %}">
            {% csrf_token %}
            <button type="submit" class="duration-500 hover:bg-red-500 bg-red-400 h-10 px-4 rounded">Удалить</button>
        </form>
    </div>
</div>

{% endblock %}

api/templates/org_list.html
{% extends 'base.html' %}
{% block title %}
org list
{% endblock %}
{% block content %}
{% load static %}


<div>
    {% for org in orgs %}
    <div class="flex gap-1">
        <form action="{% url 'api:org_select' org_id=org.id %}" method="get">
            {% if request.session.org_select == org.id %}
            <button type="submit" class="duration-500 hover:bg-indigo-500 bg-indigo-400 h-10 w-10 rounded"></button>
            {% else %}
            <button type="submit" class="duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 w-10 rounded"></button>
            {% endif %}
        </form>

        <form action="{% url 'api:org_page' org_id=org.id %}" method="get">
            <div>
                {% if request.session.org_select == org.id %}
                <button type="submit" class="w-56 text-left duration-500 hover:bg-indigo-500 bg-indigo-400 h-10 px-4 rounded">{{org.name}}</button>
                {% else %}
                <button type="submit" class="w-56 text-left duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">{{org.name}}</button>
                {% endif %}
            </div>
        </form>
    </div>
    {% endfor %}
</div>

<div class="mt-10 flex w-1/2 justify-between gap-10">
    <form action="{% url 'api:org_create' %}" method="post">
        {% csrf_token %}
        <input autocomplete="off" type="text" id="input_field" name="input_field" required maxlength="56" class="h-10 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
        <button type="submit" class="duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Создать</button>
        <label for="input_field" class="block text-sm font-medium text-zinc-300">Введите название организации</label>
    </form>
</div>
{% endblock %}

api/templates/org_page.html
{% extends 'base.html' %}
{% block title %}
org page
{% endblock %}
{% block content %}
{% load static %}

<div class="flex justify-between">
    <div>
        <form class="" method="post" action="{% url 'api:org_edit' org_id=org.id %}">
            {% csrf_token %}
            <input autocomplete="off" placeholder="{{org.name}}" type="text" id="input_field" name="input_field" required maxlength="56" class="h-10 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
            <button type="submit" class="duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Заменить</button>
            <label for="input_field" class="block text-sm font-medium text-zinc-300">Введите новое название организации</label>
        </form>
    </div>
    <div>
        <form class="" method="post" action="{% url 'api:org_delete' org_id=org.id %}">
            {% csrf_token %}
            <button type="submit" class="duration-500 hover:bg-red-500 bg-red-400 h-10 px-4 rounded">Удалить</button>
        </form>
    </div>
</div>

<div class="mt-10">
    <button class="duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded" onclick="copyToClipboard()">Скопировать ссылку для приглашения</button>
</div>


<script>
function copyToClipboard() {
    const textToCopy = "https://bitstock.sh-development.ru/org_page/invite/{{org.id}}";

    const textarea = document.createElement('textarea');
    textarea.value = textToCopy;
    document.body.appendChild(textarea);

    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);

    alert('Ссылка для добавления сотрудника скопирована');
}
</script>

{% endblock %}

api/templates/product_add.html
{% extends 'base.html' %}
{% block title %}
product_page
{% endblock %}
{% block content %}
{% load static %}


<form class="" method="post" action="{% url 'api:product_add'%}">
    {% csrf_token %}

    <div class="text-white">Название:</div>
    <div class="mb-10">
        <input autocomplete="off" type="text" name="name" class="w-1/2 h-10 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" maxlength="56">
    </div>

    <div class="text-white">Описание:</div>
    <div class="mb-10">
        <textarea autocomplete="off" name="description" class="w-1/2" rows="16"></textarea>
    </div>

    <div class="text-white">Категория:</div>
    <select name="category" class="h-10 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" required="" id="id_category">
        <option disabled>Выберите категорию</option>
        {% for category in category_list %}
            {% if category.id == product.category.id %}
                <option selected value="{{category.id}}">{{category.name}}</option>
            {% else %}
                <option value="{{category.id}}">{{category.name}}</option>
            {% endif %}
        {% endfor %}
    </select>

    <!-- <div autocomplete="off" class="text-white">Количество:</div>
    <div class="mb-10">
        <input type="number" value="1" name="count" class="w-20 h-10 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
    </div> -->
    <button type="submit" class="text-left duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Сохранить</button>

</form>



{% endblock %}

api/templates/product_category_list.html
{% extends 'base.html' %}
{% block title %}
product category list
{% endblock %}
{% block content %}
{% load static %}

<form action="" method="get" class="mb-10">
    <button type="submit" class="text-left duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Добавить</button>
</form>
<div class="flex">
    <div class="basis-2/3">
    {% for product in products %}
    <form action="{% url 'api:product_page' product_id=product.id %}" method="get" class="mt-1">
        <button type="submit" class="w-1/3 text-left duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">{{product.name}}</button>
    </form>
    {% endfor %}
    </div>

    <div class="basis-1/3">
    {% for category in categories %}
        <div class="flex gap-1 mt-1">
            <div class="flex bg-zinc-400 h-10 px-4 rounded justify-between items-center basis-2/3">
                <div>{{category.name}}</div>
            </div>

            <div>
                <form action="{% url 'api:category_delete' category_id=category.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="duration-500 hover:bg-red-500 bg-red-400 h-10 px-4 rounded basis-1/3">Удалить</button>
                </form>
            </div>
        </div>
    {% endfor %}
        <div>
            <form class="mt-10" method="post" action="{% url 'api:category_add' %}">
                {% csrf_token %}
                <input autocomplete="off"  type="text" id="input_field" name="input_field" required maxlength="56" class="h-10 w-2/3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
                <button type="submit" class="duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Создать</button>
                <label for="input_field" class="block text-sm font-medium text-zinc-300">Введите название категории</label>
            </form>
        </div>
    </div>
</div>

{% endblock %}

api/templates/product_list.html
{% extends 'base.html' %}
{% block title %}
product list
{% endblock %}
{% block content %}
{% load static %}


<div class="flex">
    <div class="w-3/4">
        {% for category, products in categories.items  %}
        <div class="mb-10">
            <h2 class="text-white text-xl">{{ category }}:</h2>
                {% for product in products %}
                <form action="{% url 'api:product_page' product_id=product.id %}" method="get" class="mt-1">
                    <button type="submit" class="w-1/2 text-left duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">{{product.name}}</button>
                </form>
                {% endfor %}
        </div>
        {% endfor %}
    </div>

    <form action="{% url 'api:product_add' %}" method="get" class="pt-8">
        {% csrf_token %}
        <button type="submit" class="text-left duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Добавить</button>
    </form>
</div>

{% endblock %}

api/templates/product_page.html
{% extends 'base.html' %}
{% block title %}
product page
{% endblock %}
{% block content %}
{% load static %}

<div class="flex justify-between">
    <div class="w-1/2">
        <form class="" method="post" action="{% url 'api:product_edit' product_id=product.id %}">
            {% csrf_token %}

            <div class="text-white">Название:</div>
            <div class="mb-10">
                <input type="text" name="name" value="{{product.name}}" class="h-10 w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" maxlength="56">
            </div>

            <div class="text-white">Описание:</div>
            <div class="mb-10">
                <textarea class="w-full" name="description" rows="16">{{product.description}}</textarea>
            </div>

            <div class="text-white">Категория:</div>
            <select name="category" class="h-10 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" required="" id="id_category">
                <option disabled>Выберите категорию</option>
                {% for category in category_list %}
                    {% if category.id == product.category.id %}
                        <option selected value="{{category.id}}">{{category.name}}</option>
                    {% else %}
                        <option value="{{category.id}}">{{category.name}}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <div class="text-white">Количество:</div>
            <div class="mb-10">
                <input type="number" name="count" value="{{product.count}}" class="w-20 h-10 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500">
            </div>

            <button type="submit" class="text-left duration-500 hover:bg-zinc-500 bg-zinc-400 h-10 px-4 rounded">Сохранить</button>
        </form>
    </div>

    <div class="">
        <form class="" method="post" action="{% url 'api:product_delete' product_id=product.id %}">
            {% csrf_token %}
            <button type="submit" class="duration-500 hover:bg-red-500 bg-red-400 h-10 px-4 rounded">Удалить</button>
        </form>
    </div>
</div>

{% endblock %}

api/templates/worker_list.html
{% extends 'base.html' %}
{% block title %}
worker list
{% endblock %}
{% block content %}
{% load static %}



{% for worker in workers %}
<div class="flex gap-10 mt-1">
    <div class="flex bg-zinc-400 h-10 px-4 rounded w-1/3 justify-between items-center">
        <div>{{worker.name}}</div>
        <div>{{worker.tg_id}}</div>
        <div>{{worker.created}}</div>
    </div>

    <div>
        <form action="{% url 'api:worker_delete' worker_tg=worker.tg_id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="duration-500 hover:bg-red-500 bg-red-400 h-10 px-4 rounded">Уволить</button>
        </form>
    </div>
</div>
{% endfor %}



{% endblock %}